Description of graph_like
graph_like
PURPOSE
graph_like(data, adj, beta, sigma): compute log p(DATA|GRAPH)
SYNOPSIS
function [logI graph] = graph_like(data, graph, ps)
DESCRIPTION
 graph_like(data, adj, beta, sigma): compute log p(DATA|GRAPH)
CROSS-REFERENCE INFORMATION
This function calls:
graph_like_conn Compute log P(DATA|GRAPH)
graph_like_rel graph_like_rel(data, adj, beta, sigma): compute log p(DATA|GRAPH), where
This function is called by:
best_split Choose the best split of cluster node C.
collapsedims take graph with multiple components and squeeze out dimensions wherever
gibbs_clean SWAPTYPES: which swaps to include
runmodel Given data set DIND, find the best instance of form SIND.
spr "Sub-tree pruning and regrafting": try changing a tree structured graph
structurefit Fit a given structure to matrix DATA using parameters PS
swapobjclust Try improving GRAPH by swapping clusters or individual objects
SOURCE CODE
function [logI graph] = graph_like(data, graph, ps)
% graph_like(data, adj, beta, sigma): compute log p(DATA|GRAPH)
origgraph = graph;
currobj = find(graph.z > 0);
if strcmp(ps.runps.type, 'sim')
  data = data(currobj, currobj);
elseif strcmp(ps.runps.type, 'feat')
  data = data(currobj,:);
elseif strcmp(ps.runps.type, 'rel')
  %data.R = data.R(currobj,currobj,:);
end
if strcmp(ps.runps.type, 'rel')
  [logI newgraph] = graph_like_rel(data, graph, ps);
else
   [logI newgraph] = graph_like_conn(data, graph, ps);
end
graph = newgraph;