Description of graph_prior
graph_prior
PURPOSE
Compute prior on graph GRAPH.
SYNOPSIS
function gp = graph_prior(graph, ps)
DESCRIPTION
 Compute prior on graph GRAPH.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
best_split Choose the best split of cluster node C.
collapsedims take graph with multiple components and squeeze out dimensions wherever
gibbs_clean SWAPTYPES: which swaps to include
runmodel Given data set DIND, find the best instance of form SIND.
spr "Sub-tree pruning and regrafting": try changing a tree structured graph
structurefit Fit a given structure to matrix DATA using parameters PS
swapobjclust Try improving GRAPH by swapping clusters or individual objects
SOURCE CODE
function gp = graph_prior(graph, ps)
% Compute prior on graph GRAPH.
% GP = log P(GRAPH).
% if some objects are out of play, gp will be proportional to the true prior
% but the actual number will be wrong
nclusternodes = size(graph.adjcluster,1);
switch graph.type
 case {'partition', 'connected', 'partitionnoself', 'connectednoself'}
   index = 1;
 case {'chain', 'undirchain', 'undirchainnoself'}
   index = 2;
 case {'ring', 'undirring', 'undirringnoself'}
   index = 3;
 case {'tree'}
   index = 4;
   nclusternodes = nclusternodes - length(graph.illegal);
 case {'hierarchy', 'undirhierarchy', 'undirhierarchynoself', 'undirdomtree', 'undirdomtreenoself'}
   index = 5;
 case {'domtree', 'dirhierarchy', 'dirhierarchynoself', 'dirdomtreenoself'}
   index = 6;
 case {'order', 'dirchain', 'dirchainnoself', 'ordernoself'}
   index = 7;
 case {'dirring', 'dirringnoself'}
   index = 8;
 case {'grid'}
   index = 9;
 case {'cylinder'}
   index = 10;
 otherwise
   error('Unexpected structure');
end
gp = ps.logps{index}(nclusternodes);