Description of inv_posdef
inv_posdef
PURPOSE
INV_POSDEF Invert positive definite matrix.
SYNOPSIS
function x = inv_posdef(A)
DESCRIPTION
 INV_POSDEF        Invert positive definite matrix.
 INV_POSDEF(A) is like INV(A) but faster and more numerically stable.
CROSS-REFERENCE INFORMATION
This function calls:
inv_triu INV_TRIU Invert upper triangular matrix.
This function is called by:
dataprobwsig Compute probability P(Wvec|D), where Wvec specifies the edge lengths for
gplike Compute log probability of data X (assume 0 mean) under a Gaussian model
SOURCE CODE
function x = inv_posdef(A)
% INV_POSDEF        Invert positive definite matrix.
% INV_POSDEF(A) is like INV(A) but faster and more numerically stable.
U = chol(A);
iU = inv_triu(U);
x = iU*iU';