Description of masterrun
masterrun
PURPOSE
Charles Kemp, 2008
SYNOPSIS
This is a script file.
DESCRIPTION
 Charles Kemp, 2008
 Fit different structures to feature, similarity and relational data
CROSS-REFERENCE INFORMATION
This function calls:
defaultps Default settings of all parameters
runmodel Given data set DIND, find the best instance of form SIND.
setps
This function is called by:
SOURCE CODE
% Charles Kemp, 2008
% Fit different structures to feature, similarity and relational data
addpath(pwd);
masterfile    = 'resultsdemo.mat';
% masterfile must have .mat suffix, otherwise exist() won't find it
if ~strcmp(masterfile(end-3:end), ['.mat'])
  error('masterfile must have a .mat suffix');
end
ps = setps();
% set default values of all parameters
ps = defaultps(ps);
% change default parameters for this run
[s,w] = system('which neato');
if s == 0 % neato available
ps.showinferredgraph = 1; % show inferred graph
ps.showpostclean     = 1; % show best graph (post cleaning) at each depth
end
ps.reloutsideinit    ='overd';   % initialize relational structure with
                 % one object per group
% Structures for this run. We'll fit the chain model, the ring model and
% the tree model. The indices correspond to form names in setpsexport()
% thisstruct = [2,4,6];
% Datasets for this run. Indices correspond to dataset names in  setpsexport()
% thisdata = [1:3];
% to run some additional structure/data pairs list them here.
extraspairs = [];
extradpairs = [];
% Use these structure and data indices for analyzing
% c) real world relational data in Kemp (2008)
% thisstruct = [1,3,9, ...   % 1: partition, 3: order, 9: partition with self loop,
%     10:13, ...  % 10: dir chain, 11: dir chain w/o selfloop, 12: undir chain, 13: undir chain w/o selfloop
%     14:16, ...  % 14: order no self, 15: connected (dunno what that is), 16: connected no selfloop
%     17:20, ...  % 17: dir ring, 18: dir ring no self, 19: undir ring, 20: undir ring no self
%     21:24  % 21: dir hierarchy, dir hierarchy no self, 23: undir hierarchy, 24: undir hierarchy no self
%     ];
thisstruct = [17];  % directed ring
% thisdata = [17:20];    % 17: mangabeys, 18: bush, 19: kularing, 20: prisoners
thisdata = [19]; % kularing
sindpair = repmat(thisstruct', 1, length(thisdata));
dindpair = repmat(thisdata, length(thisstruct), 1);
sindpair = [extraspairs(:); sindpair(:)]';
dindpair = [extradpairs(:); dindpair(:)]';
repeats = 1;
for rind = 1:repeats
  for ind = 1:length(dindpair)
    dind = dindpair(ind);
    sind = sindpair(ind);
    disp(['  ', ps.data{dind}, ' ', ps.structures{sind}]);
    rand('state', rind);
    [mtmp stmp  ntmp ltmp gtmp] = runmodel(ps, sind, dind, rind);
    succ = 0;
    while (succ == 0)
      try
        if exist(masterfile)
          currps = ps; load(masterfile); ps = currps;
     end
    pss{sind,dind,rind} = ps;
        modellike(sind, dind, rind) = mtmp;
        structure{sind,dind, rind}  = stmp;
        names{dind} = ntmp;
        llhistory{sind, dind, rind} = ltmp;
        save(masterfile, 'modellike', 'structure', 'names', 'pss', ...
             'llhistory');
        succ = 1;
      catch
        succ = 0;
        disp('error reading masterfile');
        pause(10*rand);
      end
    end
  end
end