Description of matrixpartition
matrixpartition
PURPOSE
Chop matrix J into 4 sub matrices
SYNOPSIS
function [A B C D]=matrixpartition(J, nobjects)
DESCRIPTION
 Chop matrix J into 4 sub matrices
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
dataprobwsig Compute probability P(Wvec|D), where Wvec specifies the edge lengths for
extract_weights Go through gradient matrices (dEdlWa, etc) and pull out dWvec (includes
mat2vec convert weighted graph W to a vector of weights V
SOURCE CODE
function [A B C D]=matrixpartition(J, nobjects)
% Chop matrix J into 4 sub matrices
A = J(1:nobjects, 1:nobjects);
B = J(1:nobjects, nobjects+1:end);
C = J(nobjects+1:end, 1:nobjects);
D = J(nobjects+1:end, nobjects+1:end);